apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: secret-volume
              secret:
                secretName: backupkey-secret
          containers:
            - name: backup
              image: backup:1.0
              volumeMounts:
                - name: secret-volume
                  mountPath: /home/backup/keys
              env:
                - name: STATE
                  value: backup
                - name: PGHOST
                  value: postgres-service
                - name: PGDATABASE
                  value: postgres
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: password
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: password
                - name: DBNAME
                  value: postgres
                - name: REMOTEUSER
                  value: root
                - name: REMOTEIP
                  value: storage-service
                - name: STORAGEPATH
                  value: /tmp
                - name: DATEFORMAT
                  value: "%Y-%m-%d-%H-%M"
                - name: NAMESPACE
                  value: space-2
                - name: DBAPP
                  value: test-backup
          restartPolicy: OnFailure
