apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: db
    image: postgres:12
    ports:
    - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: password