apiVersion: batch/v1
kind: Job
metadata:
  name: restore-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
            - name: secret-volume
              secret:
                secretName: backupkey-secret
      containers:
        - name: backup
          image: backup:0.4
          volumeMounts:
            - name: secret-volume
              mountPath: /home/backup/keys
          env:
            - name: STATE
              value: restore
            - name: PGHOST
              value: postgres-service
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: DBNAME
              value: postgres
            - name: BACKUPNAME
              value: ""
            - name: REMOTEUSER
              value: root
            - name: REMOTEIP
              value: storage-service
            - name: STORAGEPATH
              value: /tmp
            - name: RESTOREOPTIONS
              value: '-c'
      restartPolicy: Never