apiVersion: v1
kind: Pod
metadata:
  name: storage
  labels:
    app: storage
spec:
  containers:
  - name: storage
    image: praqma/alpine-sshd
    env:
      - name: AUTHORIZED_KEYS
        value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDW1MxzrnvkzFFxkEOLflhoZlV0MUa9WoRNXVkRX90edddq5Jke1KUCnRHRtLlESLGpSLRjMc2U7gEiqoByNhVzZqvwglUWIZvy6KAVfxJtvuwIvCrgHotfjF0XxkaeD7kA7WaZS98vdzdoPfhfI6OeqBfzjS6SRXQgjgzciZew7gfTm/dPH5KFihA+RYYVOIAcDp/UrnGRSVZj+Wzee0xNcRHyWLQ/Dowwon7+Vje7GgO4d/AV90rf+JNQaKIeDAsUFgLHfOCCxbuMGSRXtXNp0JcUnFswTuP7IEdUwwmQHwAa+63g0Jho6tfB0teETgXkiog5S2cfaQHLrnFtb9LCRxAQwbn26YtQQGIu86LBNsRyzKR76h6pwyP/hTLG8svCLrO0S+UOOawhH8nEDC7hKw+7ogcIZX8L3NVuJfL2/JQagVIpA2L5nfPLAB/nIA1h1T7MsCRBr/pigbo441mQTrq+q5tFrjbKAGQDudgjrQUriPNbny59lXmRc6xYcN6bd0HhO/SEbMr0hDOHs+oItm1NQNwYMe0huOf1jGeJWnVYculH/s36uCirWW+q3XWLCYgfiV/j0hSVaNSN06QelBssY4lGiyuOwvq3LEM5n8hs72mhDGWlTt23BlXw9Ti+jD2U/3feeQB8eGy6mv3V4IaoBxa9jOeaRJMGlqRWcw== your_email@example.com