apiVersion: v1
kind: Pod
metadata:
  name: storage
  labels:
    app: storage
spec:
  containers:
  - name: storage
    image: praqma/alpine-sshd
    env:
      - name: AUTHORIZED_KEYS
        value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDnjUpKY95x6VCfyXwz11kDyQ2/N1hPEw/j4tMG0BdrdJIV7DmjGHzBo/UibkrmhIpWxImmrjsBnMZg+mDvqrmpcs9YT+Zb4WRWIQSvx+FAIjbfyX1fDnrXn4MkpjjU+HnaE/w0jNntC0nI7HWstFxRu6QRqpMWyPXQDREN2fOcoP9wEtiZ2P3stZW7O0pFSryTQWQ+r253krKiFqVUaaPLchYRTaLBebzxohqbGY/uWOcJagIQa5WrFfG28lkR5//WVqCaKjdQ6dXp9Wr2uL5ekmQd0/eCGGCmB/rQ53xazXekb1MQbggVw85UJRP7VpljnM+fzNyiVC5i++f3uIa8FSdNLa1VMyznNU6BVeeZb7Z40QkctA8aYK/seGVJRyqYJLfLCTPjF8Uyk+/hohyM1XC+UqHgyCgRkdUtwfNlvBcGWQjlqbS7SajpM9dz1nOJDqPluFNi8b2D8tqsSek9hbYgHVwyHEYNU+BNatpTw0u1hI245i+ctoMJSo0QUsplczcDaMZH2Rp8KbAeEOc0w3R6GjaWLN+UphbMijfn9mqslF6rukkwTDzsK+AqDXI+cwaLR6E+OKGPC2SrNd628R0GsDXbveRzrCBFz2W4ZDPL9BPLlTvklyLVf3lMhmZEqcP7dmgoiJ0eAHVuu4P1+82Bb153uAbQcsttJ5IV6w== test-key

